"""
PITCHMIND — STEP 0: Cricsheet JSON → CSV Converter
====================================================
Converts all Cricsheet IPL JSON files into matches.csv + deliveries.csv
that are 100% compatible with the existing pipeline (steps 1–4).

Folder structure expected:
    data/
      Data_Cricsheet/      ← all your 1169 .json files go here
      matches.csv          ← generated by this script
      deliveries.csv       ← generated by this script

Run:
    python 0_json_to_csv.py

Then run the rest of the pipeline as normal:
    python 1_data_cleaning.py
    python 2_feature_engineering.py
    python 3_train_model.py
    streamlit run 4_dashboard.py
"""

import os
import json
import pandas as pd
from pathlib import Path
from utils import normalize_team

# ── CONFIG ────────────────────────────────────────────────────────────────────
JSON_FOLDER  = os.path.join("data", "Data_Cricsheet")
OUTPUT_DIR   = "data"
MATCHES_OUT  = os.path.join(OUTPUT_DIR, "matches.csv")
DELIVERY_OUT = os.path.join(OUTPUT_DIR, "deliveries.csv")


# ── PARSE ONE JSON FILE ───────────────────────────────────────────────────────
def parse_match(filepath):
    """
    Returns (match_row dict, list of delivery dicts) or (None, []) on error.

    matches.csv columns produced (matches 1_data_cleaning.py expectations):
        id, date, season, city, venue,
        team1, team2,
        toss_winner, toss_decision,
        winner, result, dl_applied,
        player_of_match,
        umpire1, umpire2

    deliveries.csv columns produced (matches 2_feature_engineering.py):
        match_id, inning, batting_team, bowling_team,
        over, ball,
        batter, bowler, non_striker,
        batsman_runs, extra_runs, total_runs,
        extras_type,
        is_wicket, player_dismissed, dismissal_kind, fielder
    """
    with open(filepath, encoding="utf-8") as f:
        data = json.load(f)

    info = data.get("info", {})

    # ── match id: use filename (numeric) ──────────────────────────────────────
    match_id = Path(filepath).stem

    # ── date & season ─────────────────────────────────────────────────────────
    dates = info.get("dates", [])
    date  = dates[0] if dates else "1900-01-01"
    # FIX: Always derive season from date (ignores old season column)
    season = date[:4]  # Extract year from YYYY-MM-DD format

    # ── teams ─────────────────────────────────────────────────────────────────
    teams = info.get("teams", [])
    if len(teams) < 2:
        return None, []
    team1 = normalize_team(teams[0])
    team2 = normalize_team(teams[1])

    # ── venue / city ──────────────────────────────────────────────────────────
    venue = info.get("venue", "Unknown")
    city  = info.get("city",  "Unknown")

    # ── toss ──────────────────────────────────────────────────────────────────
    toss         = info.get("toss", {})
    toss_winner  = normalize_team(toss.get("winner", team1))
    toss_decision = toss.get("decision", "bat")

    # ── outcome ───────────────────────────────────────────────────────────────
    outcome   = info.get("outcome", {})
    winner_raw = outcome.get("winner", None)
    winner    = normalize_team(winner_raw) if winner_raw else None

    # result type: "normal", "tie", "no result", "D/L"
    if "eliminator" in outcome:          # super over decider
        result = "normal"
    elif "bowl_out" in outcome:
        result = "normal"
    elif winner is None:
        result = "no result"
    elif outcome.get("method") == "D/L":
        result = "D/L"
    elif outcome.get("result") == "tie":
        result = "tie"
    else:
        result = "normal"

    dl_applied = 1 if outcome.get("method") == "D/L" else 0

    # ── player of match ───────────────────────────────────────────────────────
    pom_list = info.get("player_of_match", [])
    pom = pom_list[0] if pom_list else "Unknown"

    # ── umpires ───────────────────────────────────────────────────────────────
    officials = info.get("officials", {})
    umpires   = officials.get("umpires", [])
    umpire1   = umpires[0] if len(umpires) > 0 else "Unknown"
    umpire2   = umpires[1] if len(umpires) > 1 else "Unknown"

    match_row = {
        "id"             : match_id,
        "date"           : date,
        "season"         : season,
        "city"           : city,
        "venue"          : venue,
        "team1"          : team1,
        "team2"          : team2,
        "toss_winner"    : toss_winner,
        "toss_decision"  : toss_decision,
        "winner"         : winner,
        "result"         : result,
        "dl_applied"     : dl_applied,
        "player_of_match": pom,
        "umpire1"        : umpire1,
        "umpire2"        : umpire2,
    }

    # ── deliveries ────────────────────────────────────────────────────────────
    delivery_rows = []
    innings_data  = data.get("innings", [])

    for inning_idx, inning in enumerate(innings_data, start=1):
        # Skip super overs (inning_idx > 2)
        if inning_idx > 2:
            break

        batting_team = normalize_team(inning.get("team", ""))
        # bowling team = the other team
        bowling_team = team2 if batting_team == team1 else team1

        for over_obj in inning.get("overs", []):
            over_no = over_obj.get("over", 0)

            for ball_idx, delivery in enumerate(over_obj.get("deliveries", []), start=1):

                runs_obj      = delivery.get("runs", {})
                batsman_runs  = runs_obj.get("batter", 0)
                extra_runs    = runs_obj.get("extras", 0)
                total_runs    = runs_obj.get("total", batsman_runs + extra_runs)

                # extras type
                extras_obj   = delivery.get("extras", {})
                if extras_obj:
                    extras_type = list(extras_obj.keys())[0]
                else:
                    extras_type = None

                # wicket info
                wickets      = delivery.get("wickets", [])
                is_wicket    = 1 if wickets else 0
                player_dismissed = None
                dismissal_kind   = None
                fielder          = None

                if wickets:
                    w = wickets[0]
                    player_dismissed = w.get("player_out", None)
                    dismissal_kind   = w.get("kind", None)
                    fielders_list    = w.get("fielders", [])
                    if fielders_list:
                        fielder = fielders_list[0].get("name", None)

                delivery_rows.append({
                    "match_id"          : match_id,
                    "inning"            : inning_idx,
                    "batting_team"      : batting_team,
                    "bowling_team"      : bowling_team,
                    "over"              : over_no,
                    "ball"              : ball_idx,
                    "batter"            : delivery.get("batter", ""),
                    "bowler"            : delivery.get("bowler", ""),
                    "non_striker"       : delivery.get("non_striker", ""),
                    "batsman_runs"      : batsman_runs,
                    "extra_runs"        : extra_runs,
                    "total_runs"        : total_runs,
                    "extras_type"       : extras_type,
                    "is_wicket"         : is_wicket,
                    "player_dismissed"  : player_dismissed,
                    "dismissal_kind"    : dismissal_kind,
                    "fielder"           : fielder,
                })

    return match_row, delivery_rows


# ── MAIN ──────────────────────────────────────────────────────────────────────
def main():
    print("=" * 60)
    print("  PITCHMIND — JSON → CSV Converter")
    print("=" * 60)

    if not os.path.isdir(JSON_FOLDER):
        print(f"\n❌ Folder not found: {JSON_FOLDER}")
        print("   Make sure your JSON files are in data/Data_Cricsheet/")
        return

    json_files = [f for f in os.listdir(JSON_FOLDER) if f.endswith(".json")]
    # exclude the readme txt if any
    json_files = [f for f in json_files if not f.startswith("README")]

    print(f"\n📂 Found {len(json_files)} JSON files in {JSON_FOLDER}")
    print("   Parsing matches...\n")

    all_matches    = []
    all_deliveries = []
    errors         = []

    for i, filename in enumerate(sorted(json_files), 1):
        filepath = os.path.join(JSON_FOLDER, filename)
        try:
            match_row, delivery_rows = parse_match(filepath)
            if match_row is None:
                errors.append((filename, "teams list missing"))
                continue
            all_matches.append(match_row)
            all_deliveries.extend(delivery_rows)
        except Exception as e:
            errors.append((filename, str(e)))

        if i % 100 == 0 or i == len(json_files):
            print(f"   Processed {i}/{len(json_files)} files "
                  f"| Matches: {len(all_matches)} "
                  f"| Deliveries: {len(all_deliveries):,}")

    # ── Build DataFrames ─────────────────────────────────────────────────────
    matches_df    = pd.DataFrame(all_matches)
    deliveries_df = pd.DataFrame(all_deliveries)

    # Sort by date
    matches_df["date"] = pd.to_datetime(matches_df["date"])
    matches_df = matches_df.sort_values("date").reset_index(drop=True)

    # ── Save ─────────────────────────────────────────────────────────────────
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    matches_df.to_csv(MATCHES_OUT, index=False)
    deliveries_df.to_csv(DELIVERY_OUT, index=False)

    # ── Summary ──────────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  CONVERSION COMPLETE")
    print("=" * 60)
    print(f"  ✅ matches.csv    →  {matches_df.shape[0]:,} rows  ×  {matches_df.shape[1]} cols")
    print(f"  ✅ deliveries.csv →  {deliveries_df.shape[0]:,} rows  ×  {deliveries_df.shape[1]} cols")
    print(f"  📅 Date range     :  {matches_df['date'].min().date()}  →  {matches_df['date'].max().date()}")
    print(f"  🏆 Seasons        :  {sorted(matches_df['season'].unique())}")
    print(f"  🏏 Teams          :  {sorted(matches_df['team1'].unique())}")

    if errors:
        print(f"\n  ⚠️  {len(errors)} files had errors:")
        for fname, err in errors[:10]:
            print(f"     {fname}: {err}")
        if len(errors) > 10:
            print(f"     ... and {len(errors) - 10} more")

    print(f"\n  Saved to:")
    print(f"    {MATCHES_OUT}")
    print(f"    {DELIVERY_OUT}")

    print("\n" + "=" * 60)
    print("  Next step → python 1_data_cleaning.py")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    main()